### ISSUE TITLE
Bug? Crash from User FORUM

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/SIGNALDuino#104]
@sidey79 
[schau dir bitte mal den Beitrag an bitte](https://forum.fhem.de/index.php/topic,94327.msg872743.html?PHPSESSID=gakvbrqp1pj8soh2lqhigj1ud3#msg872743). Kann es sein das sowas passiert wie der User beschrieb?

**Comment by sidey79** [comment]
Zum Flashen wird avrdude aufgerufen.
Das konnte aber nicht flashen.
