### ISSUE TITLE
send.h - Array zu klein für Protokoll 87 Jarolift

### ISSUE THREAD

**Issue by elektron-bbs** [RFD-FHEM/SIGNALDuino#109]
Durch den Einbau der zusätzlich Timings für dieses spezielle Protokoll ist jetzt das Array

	int16_t buckets[6];

in der Datei "send.h" zu klein. Wir benötigen dafür wenigstens eine Größe von 7.
Es könnten aber auch noch mehr werden:

foreach my $item (qw(preSync sync start one zero float pause end universal))

**Comment by HomeAutoUser** [comment]
@sidey79, ist es möglich diese Anpassung in die Dev mit zu übernehmen oder wurde es manchmal schon gemacht?
