### ISSUE TITLE
Firmware-Dateien 3.5.0-dev+20201207

### ISSUE THREAD

**Issue by elektron-bbs** [RFD-FHEM/SIGNALDuino#199]
Irgendwie kann ich keinen Link zu Firmware-Dateien 3.5.0-dev+20201207 mehr erstellen (siehe https://forum.fhem.de/index.php/topic,83273.msg1154865.html#msg1154865). Ich sehe bzw. sah dort zwar einen Draft (den habe ich evtl. eben aus Versehen gelöscht - Sorry), aber ohne Github-Account kam offensichtlich nur eine Fehlermeldung.
Auch aus FHEM (set flash) ist diese Version nicht mehr verfügbar.

**Comment by sidey79** [comment]
Es fehlen also compilierten Versionen einer 3.5.0 Version richtig?

**Comment by elektron-bbs** [comment]
Ja, genauu so ist es.

**Comment by sidey79** [comment]
Ich habe ein Release wieder angelegt. Sollte noch was fehlen, dann einfach wieder melden.

https://github.com/RFD-FHEM/SIGNALDuino/releases/tag/3.5.0-dev%2B20201221
