### ISSUE TITLE
Extension: Rohrmotor24

### ISSUE THREAD

**Issue by thoffma3** [RFD-FHEM/SIGNALDuino#22]
Das Protokoll ist entschlüsselt und es gibt schon Eigenbaulösungen. Siehe hier:
http://www.mikrocontroller.net/topic/242784?goto=3962231#3962231

In Github existiert bereits ein Implementierung (aber nicht für Fhem):
https://github.com/bjwelker/Raspi-Rollo

Das ist auch ein gute Quelle 
http://physudo.blogspot.de/2013/08/home-automation-mit-dem-arduino-und-433_17.html
http://physudo.blogspot.de/2013/08/home-automation-mit-dem-arduino-und-433_18.html

**Comment by sidey79** [comment]
Das Signal wird doch vom Arduino bereits erkannt oder?

**Comment by thoffma3** [comment]
Hallo Sidey. Blicke grad nicht durch. Hab auch einige Wochen nichts gemacht. Hast du das jetzt was implementiert was ich testen kann? Signalduino hab ich grad aktualisiert und ist jetzt bei mir frisch auf dem Fhem

**Comment by sidey79** [comment]
Ich gestehe, ich habe mit dem Rohrmotor so gut wie nichts gemacht.
Der Arduino müsste das Signal ja bereits erkennen und an FHEM übergeben. Daher habe ich dein Anliegen referenziert. Der Arduino Code und der FHEM Code liegen in getrennten repos. Ich bau dir mal schnell die Rohrmotor Erkennung ein, dann kannst Du das testen.

**Comment by Jarnsen** [comment]
Hallo,
hat sich inzwischen was getan?? Erkannt wird der Code ja. Senden kann ich ihn aber leider nicht. Da passiert nichts. Kann man da was einbauen das es als QuadState gesendet wird?? würde ja erstmal reichen.

**Comment by sidey79** [comment]
Hallo Jarnsen,

Leider hatte bislang niemand Signaldaten zur Verfügung gestellt.

Ich kann die Demodulierung jetzt anpassen.
Senden sollte auch gehen. Beispiel kommt später.

**Comment by Jarnsen** [comment]
Ok danke...

Wenn ich noch irgendwas beisteuern kann sag bescheid..... Im Microcontroller Forum wurde sogar die ausgelesene Firmenware eines Handsenders hinterlegt...

Stelle mich gern zum testen bereit....

**Comment by sidey79** [comment]
details at RFDHEM\RFFHEM#19
