### ISSUE TITLE
Empfang X10 bzw. X10-Security-Protocol

### ISSUE THREAD

**Issue by wherzig** [RFD-FHEM/SIGNALDuino#33]
Hallo,

ist es möglich mit SIGNALDuino das X10-Protokoll zu empfangen bzw. zu decodieren. 

Wenn ich mir den Empfang des X10-Security-Sensors ansehe, bekomme ich folgende Logs. Ich habe jeweils davor geschrieben, was im Hexcode herauskommen soll.

Kann man damit etwas anfangen?

Das basierende X10-RF Protocol ist her beschrieben:
- http://openmicros.org/media/kunena/attachments/987/X10_RF_Receiver.pdf
oder
- http://www.authinx.com/manuals/activehome/xtdcode.pdf

"Data is accepted bit by bit as the presence or absence of 120Khz
carrier occurring after the positive or negative mains zero crossing.
The acceptance window begins approximately 250 usecs. and ends
approximately 900 usecs. after a zero crossing. In this window 48 or
more cycle of carrier are accepted as a "1" bit and fewer than 48 as a
"0" bit. Except for the Startcode, each bit of data is sent in its
true and complement form. "

In rtl_433 ist X10 testweise wie folgt codiert:
r_device X10_RF = {
        .name                   = "X10 RF",
        .modulation             = OOK_PULSE_PPM_RAW,
        .short_limit    = 1100, // Short gap 500µs, long gap 1680µs
        .long_limit             = 2800, // Gap after sync is 4.5ms (1125)
        .reset_limit    = 6000, // Gap seen between messages is ~40ms so let's get them individually
        .json_callback  = &X10_RF_callback,
        .disabled               = 0,
        .demod_arg              = 0,
};

Wie gehe ich am besten vor?

Man muss das Protokoll definieren. Klar.
Also so etwas:
    "39"    => 			## X10 Protocol
        {
            name			=> 'X10 Protocol',	
			id          	=> '39',
			one			=> [1,-2],
			zero			=> [2,-2],
			#sync			=> [1,-8],		# 
			clockabs     	=> 470,			# 
			format 			=> 'twostate',	    # 
			preamble		=> '"',		# prepend to converted message	
			clientmodule    => 'RFXX10REC',   	# not used now
			#modulematch     => '^TX......', # not used now
			length_min      => '43',
			length_max      => '44',
			remove_zero     => 1,           # Removes leading zeros from output

		}, 	  

Aber was kommt bei den einzelnen Werten hin?
Was bedeuten die Angaben bei one, zero, clockabs, ....

Ist format twostate richtig?

Grüße

Willi

---------------------

DS10A Kontakt geschlossen

Zu demodulierender Hexcode 29454a847bd700

2016.02.15 18:05:02 4: sduino/msg READ: MU;P0=658;P1=-581;P2=-1720;P4=10748;P5=-2688;D=0101010201020102010102010201020101010102010101020202020102020202010201020202010045010201010102010201020101020102010201010101020101010202020201020202020102010202020100;CP=0;
2016.02.15 18:05:02 4: sduino: Fingerprint for MU Protocol id 27 -> remote27 matches, trying to demodulate
2016.02.15 18:05:02 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2016.02.15 18:05:02 4: sduino: Fingerprint for MU Protocol id 31 -> pollin isotronic matches, trying to demodulate
2016.02.15 18:05:02 4: sduino: Fingerprint for MU Protocol id 36 -> socket36 matches, trying to demodulate
2016.02.15 18:05:02 4: sduino: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2016.02.15 18:05:02 4: sduino/msg READ: MU;P0=656;P1=10710;P2=-2730;P3=-586;P4=-1716;D=01203040303030403040304030304030403040303030304030303040404040304040404030403040404030012030403030304030403040303040304030403030303040303030404040403040404040304030404040300;CP=0;
2016.02.15 18:05:02 4: sduino: Fingerprint for MU Protocol id 27 -> remote27 matches, trying to demodulate
2016.02.15 18:05:02 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2016.02.15 18:05:02 4: sduino: Fingerprint for MU Protocol id 31 -> pollin isotronic matches, trying to demodulate
2016.02.15 18:05:02 4: sduino: Fingerprint for MU Protocol id 36 -> socket36 matches, trying to demodulate
2016.02.15 18:05:02 4: sduino: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2016.02.15 18:05:02 4: sduino/msg READ: MU;P0=-3556;P1=10708;P2=-2720;P3=550;P4=-583;P5=-1711;D=01234353434343534353435343435343534353434343435343434353535353435353535343534353535343;CP=3;
2016.02.15 18:05:02 4: sduino: Fingerprint for MU Protocol id 16 -> Dooya shutter matches, trying to demodulate
2016.02.15 18:05:02 4: sduino: Fingerprint for MU Protocol id 27 -> remote27 matches, trying to demodulate
2016.02.15 18:05:02 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2016.02.15 18:05:02 4: sduino: Fingerprint for MU Protocol id 30 -> unitec47031 matches, trying to demodulate
2016.02.15 18:05:02 4: sduino: Fingerprint for MU Protocol id 36 -> socket36 matches, trying to demodulate
2016.02.15 18:05:02 4: sduino: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate

------------------------------------------------------------------
DS10A Kontakt offen

Zu demodulierender Hexcode 29454a04fbd700

2016.02.15 18:06:35 4: sduino/msg READ: MS;P0=546;P1=-587;P2=-1721;P3=-15617;P4=10642;P5=-2802;D=03450102010101020102010201010201020101010101010201010202020202010202020201020102020201;CP=0;SP=3;O;
2016.02.15 18:06:35 4: sduino/msg READ: MU;P0=-2796;P1=544;P2=-587;P3=-1722;P4=-32001;P5=120;D=01213121212131213121312121312131212121212121312121313131313121313131312131213131312145;CP=1;
2016.02.15 18:06:35 4: sduino: Fingerprint for MU Protocol id 16 -> Dooya shutter matches, trying to demodulate
2016.02.15 18:06:35 4: sduino: Fingerprint for MU Protocol id 27 -> remote27 matches, trying to demodulate
2016.02.15 18:06:35 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2016.02.15 18:06:35 4: sduino: Fingerprint for MU Protocol id 30 -> unitec47031 matches, trying to demodulate
2016.02.15 18:06:35 4: sduino: Fingerprint for MU Protocol id 36 -> socket36 matches, trying to demodulate
2016.02.15 18:06:35 4: sduino: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2016.02.15 18:06:35 4: sduino/msg READ: MU;P0=-1526;P2=10644;P3=-2792;P4=549;P5=-583;D=023454004545454045404540454540454045454545454540454540404040404540404040454045404040454;CP=4;
2016.02.15 18:06:35 4: sduino: Fingerprint for MU Protocol id 16 -> Dooya shutter matches, trying to demodulate
2016.02.15 18:06:35 4: sduino: Fingerprint for MU Protocol id 27 -> remote27 matches, trying to demodulate
2016.02.15 18:06:35 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2016.02.15 18:06:35 4: sduino: Fingerprint for MU Protocol id 30 -> unitec47031 matches, trying to demodulate
2016.02.15 18:06:35 4: sduino: Fingerprint for MU Protocol id 36 -> socket36 matches, trying to demodulate
2016.02.15 18:06:35 4: sduino: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate

**Comment by sidey79** [comment]
Geschlossen, da es im FHEM Modul zu implementieren ist :)
