### ISSUE TITLE
Code explanation

### ISSUE THREAD

**Issue by joeleejoelee** [RFD-FHEM/SIGNALDuino#36]
Hi everyone, 
I m not sure, if this is the right way to ask for code  explanation.
Could somebody explain the following Code from SIGNALduino? 
[code#define portOfPin(P)\
  (((P)>=0&&(P)<8)?&PORTD:(((P)>7&&(P)<14)?&PORTB:&PORTC))
#define ddrOfPin(P)\
  (((P)>=0&&(P)<8)?&DDRD:(((P)>7&&(P)<14)?&DDRB:&DDRC))
#define pinOfPin(P)\
  (((P)>=0&&(P)<8)?&PIND:(((P)>7&&(P)<14)?&PINB:&PINC))
#define pinIndex(P)((uint8_t)(P>13?P-14:P&7))
#define pinMask(P)((uint8_t)(1<<pinIndex(P)))

#define pinAsInput(P) *(ddrOfPin(P))&=~pinMask(P)
#define pinAsInputPullUp(P) *(ddrOfPin(P))&=~pinMask(P);digitalHigh(P)
#define pinAsOutput(P) *(ddrOfPin(P))|=pinMask(P)
#define digitalLow(P) *(portOfPin(P))&=~pinMask(P)
#define digitalHigh(P) *(portOfPin(P))|=pinMask(P)
#define isHigh(P)((*(pinOfPin(P))& pinMask(P))>0)
#define isLow(P)((*(pinOfPin(P))& pinMask(P))==0)
#define digitalState(P)((uint8_t)isHigh(P))[/code]

I would like to port that to another device.

**Comment by sidey79** [comment]
Hi,

it's not developed by me,
In general, is it a set of macros, which alter the registers of the microcontroller.
This is faster, compared to the arduino cpp functions provided for that task.

More details can be found here:
http://masteringarduino.blogspot.de/2013/10/fastest-and-smallest-digitalread-and.html
