### ISSUE TITLE
RSL Protokoll (Conrad)

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/SIGNALDuino#7]
Conrad RSL Protokoll:

SyncBit: 1xHIGH 10xLOW
1:  2xHIGH 1xLOW
0:  1xHIGH 2xLOW
Clock: 650

Für welche Geäte das alles gilt ist mir nicht bekannt.
Quelle: http://www.mikrocontroller.net/topic/252895

**Comment by sidey79** [comment]
Test durch von dKahn:

SyncBit: 1xHIGH 11xLOW
1: 2xHIGH 1xLOW
0: 1xHIGH 2xLOW
Clock: 560

Beispiele:

M1;P0=520;P1=-6148;P2=1160;P3=-508;P4=-1096;P5=-32001;P6=1433;D=012304230404040404232304042304230423040404230423040404040423230404;CP=0;SP=1; 
Dekodiert -> S10100000110010101000101000001100


M1;P0=568;P1=-1112;P2=1136;P3=-544;P4=-3704;P5=-6152;P6=1433;D=052301230123010101232301012301230123010101230123010101010123230101;CP=0;SP=5; 
Dekodiert -> S10101000110010101000101000001100

**Comment by sidey79** [comment]
Wird als MS erkannt und an FHEM übergeben

**Comment by Ralf9** [comment]
Da ich unter https://github.com/RFD-FHEM/RFFHEM für Conrad RSL kein issues gefunden habe, schreibe ich es mal hier dazu.
So wie es aussieht gibt es bei Conrad RSL eine neue Version mit einem 32-bit code
https://forum.fhem.de/index.php/topic,78696.0.html
https://forum.fhem.de/index.php/topic,78904.msg708531.html#msg708531

Sduino/msg READ: MU;P0=-1365;P1=477;P2=1145;P3=-734;P4=-6332;D=01023202310102323102423102323102323101023232323101010232323231023102323102310102323102423102323102323101023232323101010232323231023102323102310102323102423102323102323101023232323101010232323231023102323102310102323102423102323102323101023232323101010232;CP=1;R=12;O

```
"75" =
   {
      name => 'ConradRSL2', 
      id => '75',
      one => [3,-1],
      zero => [1,-3],
      clockabs => 500, 
      format => 'twostate', 
      preamble => 'P1RSL2#', 
      clientmodule => 'SD_RSL2', 
      modulematch => '^P1RSL2#[A-Fa-f0-9]{8}', 
      length_min => '32',
   },
```
Die Änderungen in der ConradRSL2 sind nur minimal. Die größte Änderung ist eine andere @RSL2Codes
```
my @RSL2Codes;
	# Code definition
	# [1-2]	= 2-bit Startcode   (Paket startet immer mit 10)
	# [3-4] = 2-bit Tastenpaar  (1-4)
	# [5]   = 1-bit An-Aus		(0-1)
	# [6-7] = 2-Bit Wahlschalter (1-4)
	# [8-32]= 24-bit ID (1-16777215)
	
    # Tastenpaar [1 - 4] , Schiebeschalter/Kanal [I - IV] , an-aus [1 - 0] 
 
    $RSL2Codes[1][1][0] = 0b10111110;   # 1 / I    off
    $RSL2Codes[1][1][1] = 0b10110110;   # 1 / I    on
    $RSL2Codes[1][2][0] = 0b10000001;   # 2 / I    off   
    $RSL2Codes[1][2][1] = 0b10001110;   # 2 / I    on
    $RSL2Codes[1][3][0] = 0b10101110;   # 3 / I    off
    $RSL2Codes[1][3][1] = 0b10100110;   # 3 / I    on 
    $RSL2Codes[1][4][0] = 0b10011110;   # 4 / I    off 
    $RSL2Codes[1][4][1] = 0b10010110;   # 4 / I    on  
    $RSL2Codes[2][1][0] = 0b10110101;   # 1 / II   off
    $RSL2Codes[2][1][1] = 0b10111001;   # 1 / II   on
    ....

```
Die neue Version (RSL2) müsste sich doch in die vorhandene 14_SD_RSL integrieren lassen.
```
my @RSLCodes;

    # Tastenpaar [1 - 3] , Schiebeschalter/Kanal [I - IV] , an-aus [1 - 0] 
    $RSLCodes[0][0][0][0] =  62;   # ? / ?    off  
    $RSLCodes[0][0][0][1] =  54;   # ? / ?    on   
    $RSLCodes[0][1][1][0] =   1;   # 1 / I    off
    $RSLCodes[0][1][1][1] =  14;   # 1 / I    on
    $RSLCodes[0][1][2][0] =  46;   # 2 / I    off   
    $RSLCodes[0][1][2][1] =  38;   # 2 / I    on
    ...
 #RSL2
    $RSL2Codes[1][1][1][0] = 0b10111110;   # 1 / I    off
    $RSL2Codes[1][1][1][1] = 0b10110110;   # 1 / I    on
    $RSL2Codes[1][1][2][0] = 0b10000001;   # 2 / I    off   
    $RSL2Codes[1][1][2][1] = 0b10001110;   # 2 / I    on
    ...
```

**Comment by Ralf9** [comment]
Mir ist gerade aufgefallen, daß in der 14_SD_RSL in der Parse Routine beim anlegen eines devicecodes noch ein Fehler ist 
```
DEF        B1A800_2_2 
NAME       RSL_B1A800_2_2 
```
Das DEF beginnt nicht mit "RSL_"

PS: kann man issues verschieben? dieses hier gehört eigentlich nach https://github.com/RFD-FHEM/RFFHEM
