### ISSUE TITLE
Anfrage ggf. Zusammenhang mit FW

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/SIGNALDuino#83]
Hallo @sidey79,
[kann das](https://forum.fhem.de/index.php/topic,76983.0.html) mit der Firmware zusammenhängen ?
Ich muss fragen, da ich gestern das im Zusammenhang erneuert habe.

MfG

**Comment by sidey79** [comment]
Kann ich mir nicht erklären, was die Firmware damit zu tun haben könnte.
Sorry.

**Comment by sidey79** [comment]
können wir schließen oder?
