### ISSUE TITLE
miniCUL: PIN_MARK433 ist ein analog Pin

### ISSUE THREAD

**Issue by habeIchVergessen** [RFD-FHEM/SIGNALDuino#85]
branch dev-cc1101-mcfirtbitfix

**Comment by sidey79** [comment]
Ich bin unsicher, was das Problem ist.

**Comment by habeIchVergessen** [comment]
Pin 23 am atmega328p ist A0
mit der [Anpassung](https://github.com/habeIchVergessen/SIGNALDuino/blob/a808d3bf81276728664d56b80b51017e78691e91/RF_Receiver/RF_Receiver.ino#L73) funktioniert die 433MHz CUL Erkennung

**Comment by sidey79** [comment]
Ah verstehe, oder ich schreibe A0 anstelle von 0.
Das wäre ja das gleiche

**Comment by habeIchVergessen** [comment]
kann ich gerne mal testen

**Comment by sidey79** [comment]
@habeIchVergessen 
sollte dann mit 8f7418eb1012dc75ee458b5d5c1a8be25e52548b behoben sein.
