### ISSUE TITLE
Fehlerhafte Implementierung TFA 47.3003 Funk-Regenmess-Station "Monsun"

### ISSUE THREAD

**Issue by Heinzelschelm** [RFD-FHEM/SIGNALDuino#93]
Hallo zusammen,

ich habe mir die TFA Funk-Regenmesser „Monsun” 47.3003 gekauft und habe bislang die Daten erfolgreich mit einem Signalduino (nano mit CC1101 Chip) in FHEM eingelesen. Das hat soweit alles gut funktioniert. Die Signale wurden automatisch erkannt (als KW9010 mit dem Modul CUL_TCM97001).

Eigentlich ist die Empfangsstation eine TFA Dorstmann KW9015

Die KW9010 misst Temperatur und Feuchtigkeit, die KW 9015 misst Temperatur und Niederschlagsmenge.

Der Regenmesser besteht aus einem Temperatursensor und einer Wippe. Jeder Ausschlag der Wippe erhöht die Humidity um 1. Der Temperaturwert wurde sofort richtig ausgewertet.

Man konnte sich also in FHEM einen Deltawert berechnen lassen den man mit dem Volumen der Wippe multiplizierte um sich die Niederschlagsmenge in mm plotten zu lassen. TOP

Das Problem begann nun als der Wert für Humidity von 99 auf 100 gestiegen ist. Das Modul akzeptiert nämlich keine Werte für Humidity größer als 99 (macht ja auch keinen Sinn, denn der Wert wird ja "eigentlich" als relative Feuchte benutzt). Es werden seitdem keinerlei valide Werte von der Funkstation empfangen, ich denke sie werden einfach verworfen, da der Wertebereich für Humidity überschritten wurde, man kann das im Logfile auch gut nachvollziehen...

Wie kann ich jetzt für Humidity Werte größer als 99 erlauben? Kann ich das selber verändern?
Achja, ich verwende folgende Version: V 3.3.1-RC4 SIGNALduino cc1101 - compiled at Mar 10 2018 23:20:23

Danke und mit freundlichen Grüßen, Hannes

**Comment by sidey79** [comment]
Wenn ich richtig verstehe, dann wird die Definition vom Modul CUL_TCM97001 bereitgestellt?

Dan hat das ganze Verhalten nichts mit dem SIGNALduino uC zu tun.
https://fhem.de/MAINTAINER.txt

**Comment by Heinzelschelm** [comment]
Danke, dann kann ich das hier schließen...
