### ISSUE TITLE
filter.h missing

### ISSUE THREAD

**Issue by HeinzMu** [RFD-FHEM/SIGNALDuino#97]
Ich wollte RF_receiver mit nicht definiertem "CMP_FIFO" compilieren und bekomme dabei die Fehlermeldung "filtering.h" is missing. Könntest du die bitte mit im Projekt ablegen?!

**Comment by HeinzMu** [comment]
Ich war einfach so am rumexperimentieren und bin dadurch darauf gestossen.

**Comment by sidey79** [comment]
können wir den Fall schließen?

**Comment by HeinzMu** [comment]
ja.
